version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  security-pipeline:
    docker:
      - image: cimg/node:20.5
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            cd backend && npm ci --legacy-peer-deps
            cd ../frontend && npm ci --legacy-peer-deps

      - run:
          name: Run Tests
          command: |
            cd backend
            npm test || echo "No backend tests yet"
            cd ../frontend
            npm test || echo "No frontend tests yet"

      - run:
          name: Dependency Audit
          command: |
            cd backend && npm audit --audit-level=high || true
            cd ../frontend && npm audit --audit-level=high || true

       - run:
          name: SonarCloud Scan
          command: |
            cd backend
            npm install sonar-scanner --save-dev
            # Give execute permissions to the scanner
            chmod +x node_modules/sonar-scanner/bin/sonar-scanner
            npx sonar-scanner \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORG_KEY} \
              -Dsonar.sources=. \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}

      - run:
          name: Run API Tests
          command: |
            npm install newman --save-dev
            newman run postman/KnoxBank_API_Tests.postman_collection.json --reporters cli,junit

workflows:
  version: 2
  security_scan_workflow:
    jobs:
      - security-pipeline
